
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  datasource:
    url: jdbc:mysql://localhost:3306/computer_shop?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 2662600
    driverClassName: com.mysql.jdbc.Driver
